// File: vitest.config.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

/**
 * Vitest Configuration for MOTHER v82.4
 * 
 * Fix NC-002: Implementar suite de testes automatizados
 * Target: 80% coverage em módulos críticos
 * 
 * Referências:
 * - IEEE 1028-2008: Software Reviews and Audits
 * - ISTQB Foundation Level Syllabus 2023
 * - Google Testing Blog: Testing at Scale
 */

import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: [
      'server/**/__tests__/**/*.test.ts',
      'server/**/*.test.ts',
      'tests/**/*.spec.ts',
      'tests/**/*.test.ts',
    ],
    exclude: ['node_modules/**', 'dist/**', 'client/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: ['server/**/*.ts'],
      exclude: [
        'node_modules/**',
        'dist/**',
        '**/*.d.ts',
        '**/*.config.*',
        '**/__tests__/**',
        '**/*.test.ts',
        'server/_core/production-entry.ts', // Entry point — testar via integration
      ],
      thresholds: {
        lines: 60,
        functions: 60,
        branches: 55,
        statements: 60,
      },
    },
    setupFiles: ['./tests/setup.ts'],
    testTimeout: 60000,
    hookTimeout: 15000,
    reporter: ['verbose'],
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './server'),
      '@tests': resolve(__dirname, './tests'),
    },
  },
});
