// File: tests/setup.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

/**
 * Test Setup for MOTHER v82.4
 * Configura ambiente de testes com mocks de serviços externos
 */

import { afterEach, beforeAll, vi } from 'vitest';

// Configurar variáveis de ambiente para testes
process.env.NODE_ENV = 'test';
process.env.DATABASE_URL = 'mysql://test:test@localhost:3306/mother_test';
process.env.MQTT_BROKER_URL = 'mqtt://localhost:1883';
process.env.OPENAI_API_KEY = 'test-key-not-real';
process.env.ANTHROPIC_API_KEY = 'test-key-not-real';

// Mock global de serviços externos
vi.mock('../server/services/database', () => ({
  db: {
    query: vi.fn().mockResolvedValue([]),
    execute: vi.fn().mockResolvedValue({ affectedRows: 1 }),
  },
}));

vi.mock('../server/services/llm', () => ({
  callLLM: vi.fn().mockResolvedValue({
    content: 'Mock LLM response for testing',
    tokens: 100,
    model: 'mock-model',
  }),
}));

// Limpar mocks após cada teste
afterEach(() => {
  vi.clearAllMocks();
});

// Timeout global
beforeAll(() => {
  vi.setConfig({ testTimeout: 30000 });
});
