-- migrations/001_shms_timescaledb_conselho.sql
-- Fix SHMS: Schema para dados de sensores geotécnicos
-- Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit
-- Protocolo Delphi + MAD — 3 Rodadas | Ciclo 194 | 2026-03-08
-- Referência: TimescaleDB Best Practices + ICOLD Bulletin 158 §4.3

-- Extensão TimescaleDB
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Tabela principal de leituras de sensores
CREATE TABLE IF NOT EXISTS sensor_data_conselho (
  time        TIMESTAMPTZ NOT NULL,
  sensor_id   TEXT NOT NULL,
  sensor_type TEXT NOT NULL CHECK (sensor_type IN ('piezometer', 'inclinometer', 'settlement', 'seismic', 'water_level')),
  value       DOUBLE PRECISION NOT NULL,
  unit        TEXT NOT NULL,
  quality     TEXT NOT NULL DEFAULT 'good' CHECK (quality IN ('good', 'uncertain', 'bad')),
  structure   TEXT NOT NULL,
  zone        TEXT NOT NULL,
  depth_m     DOUBLE PRECISION,
  metadata    JSONB DEFAULT '{}'
);

-- Converter para hypertable (particionamento automático por tempo)
SELECT create_hypertable('sensor_data_conselho', 'time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);

-- Índices para queries em tempo real
CREATE INDEX IF NOT EXISTS idx_sensor_data_c_sensor_time ON sensor_data_conselho (sensor_id, time DESC);
CREATE INDEX IF NOT EXISTS idx_sensor_data_c_type_time ON sensor_data_conselho (sensor_type, time DESC);

-- Tabela de alertas ICOLD
CREATE TABLE IF NOT EXISTS icold_alerts_conselho (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  level           TEXT NOT NULL CHECK (level IN ('L1', 'L2', 'L3')),
  sensor_id       TEXT NOT NULL,
  sensor_type     TEXT NOT NULL,
  value           DOUBLE PRECISION NOT NULL,
  threshold       DOUBLE PRECISION NOT NULL,
  message         TEXT NOT NULL,
  acknowledged    BOOLEAN DEFAULT FALSE,
  acknowledged_by TEXT,
  acknowledged_at TIMESTAMPTZ,
  resolved_at     TIMESTAMPTZ
);

SELECT create_hypertable('icold_alerts_conselho', 'time', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS idx_icold_alerts_c_sensor_time ON icold_alerts_conselho (sensor_id, time DESC);
CREATE INDEX IF NOT EXISTS idx_icold_alerts_c_level ON icold_alerts_conselho (level, acknowledged, time DESC);

COMMENT ON TABLE sensor_data_conselho IS 'Leituras em tempo real de sensores geotécnicos — ICOLD Bulletin 158 | Conselho C194';
COMMENT ON TABLE icold_alerts_conselho IS 'Alertas de monitoramento ICOLD L1/L2/L3 — GISTM 2020 | Conselho C194';
