-- Migration 0019: v74.10 Scientific Knowledge — Build Fix & DGM Proposal Failures
-- Acquired during: diagnosis of Cloud Build TypeScript failures and DGM write_own_code failures
-- Date: 2026-02-28

INSERT INTO knowledge (title, content, source, category, tags, created_at, updated_at) VALUES

-- NC-BUILD-001: TypeScript errors block Cloud Build
('NC-BUILD-001: TypeScript Strict Mode in CI/CD Pipelines',
'Cloud Build executes `npx tsc --noEmit` before deploying. Any TypeScript error (TS2339, TS2345, TS2304) causes the build step to exit with code 1, blocking all subsequent steps including the Docker build and Cloud Run deploy. This is the correct behavior per Dijkstra (1988) — static verification before deployment. Root cause of MOTHER deploy being stuck at v74.5: commits v74.6-v74.9 introduced 4 TypeScript errors: (1) guardian.ts used GuardianPatchResult.violated instead of .completenessViolation; (2) fitness_scorer.ts used LogComponent "fitness" which is not in the union type; (3) patch-integration.ts exported FetchRetryOptions instead of RetryOptions and CRAGEvaluation instead of CRAGMetrics; (4) mother.property.test.ts was included in the server tsconfig and referenced better-sqlite3 which was not installed. Fix: correct all type mismatches and exclude *.test.ts from tsconfig.server.json. Verification: `npx tsc --noEmit` exits with code 0.',
'Static analysis: Dijkstra (1988) "On the Cruelty of Really Teaching Computing Science"; TypeScript Handbook (Microsoft, 2024)',
'engineering',
'["typescript", "ci-cd", "cloud-build", "static-analysis", "nc-build-001"]',
NOW(), NOW()),

-- NC-BUILD-002: git push without auth in Cloud Run
('NC-BUILD-002: GitHub Authentication in Containerized Environments (Cloud Run)',
'Cloud Run containers run as ephemeral instances with no persistent filesystem, no ~/.gitconfig, no SSH keys, and no credential helpers. When MOTHER executes `git push origin main` inside Cloud Run (via self-code-writer.ts), the push fails silently with "Authentication failed" or "repository not found" because there is no GitHub token configured. This is the root cause of ALL DGM proposal failures for "Reduce Response Latency: Implement Parallel Knowledge Retrieval" — the write_own_code tool successfully writes the file but the git push fails, leaving the proposal in "failed" status. Fix: inject GITHUB_TOKEN environment variable into the Cloud Run service, then in gitCommitAndPush() call configureGitAuth() which sets the remote URL to https://x-access-token:${GITHUB_TOKEN}@github.com/... before pushing. Scientific basis: GitHub REST API authentication documentation (GitHub Docs, 2024); OAuth token in URL is the standard pattern for CI/CD headless authentication.',
'GitHub Docs (2024) "About authentication to GitHub"; Google Cloud Run docs "Environment variables and secrets"',
'security',
'["github", "cloud-run", "authentication", "git-push", "nc-build-002", "self-code-writer"]',
NOW(), NOW()),

-- DGM Parallel Knowledge Retrieval
('DGM Proposal: Parallel Knowledge Retrieval — Root Cause Analysis',
'The DGM self-proposal "Reduce Response Latency: Implement Parallel Knowledge Retrieval" appeared multiple times with status "failed" in the MOTHER interface (visible in screenshot, v74.5 production). The proposal was generated by self-proposal-engine.ts when average response time exceeded the latency threshold. The proposal hypothesis is correct: running knowledge retrieval, episodic memory search, and user memory retrieval in parallel via Promise.all() instead of sequentially reduces latency. The failure was NOT in the proposal logic but in the deployment mechanism — write_own_code could not push to GitHub from Cloud Run (NC-BUILD-002). Once GITHUB_TOKEN is configured as a Cloud Run environment variable and self-code-writer.ts injects it via configureGitAuth(), the proposal will succeed. Implementation: in core.ts, replace sequential await knowledgeSearch(); await episodicSearch(); await userMemorySearch() with const [knowledge, episodic, userMem] = await Promise.all([knowledgeSearch(), episodicSearch(), userMemorySearch()]). Expected latency reduction: 40-60% for queries that use all three knowledge sources.',
'Promise.all() MDN Web Docs (2024); AgentBench latency metrics (Liu et al., arXiv:2308.03688)',
'architecture',
'["dgm", "parallel", "knowledge-retrieval", "promise-all", "latency", "self-proposal"]',
NOW(), NOW()),

-- Google SRE Four Golden Signals applied to MOTHER
('Google SRE Four Golden Signals Applied to MOTHER v74.x',
'The Four Golden Signals (Beyer et al., Google SRE Book Ch.6, 2016) applied to MOTHER: (1) Latency — target p95 < 8000ms for streaming responses; current baseline unknown due to missing reliabilityLogger.recordQuery() calls in core.ts. (2) Traffic — queries per minute; visible in MOTHER interface as "Mensagens: 0" per session. (3) Errors — target < 1% error rate; DGM proposal failures inflate this metric. (4) Saturation — Cloud Run max instances and memory limits. The reliability monitor (ReliabilityMonitor.tsx + /api/reliability-metrics SSE endpoint) was implemented in v74.9 but lacks real data because core.ts does not yet call reliabilityLogger.recordQuery() after each query. This is the highest-priority remaining action for v74.10: add reliabilityLogger.recordQuery() call in core.ts processQuery() function.',
'Beyer et al. (2016) "Site Reliability Engineering" Ch.6 — Monitoring Distributed Systems; Google SRE Book (O''Reilly)',
'monitoring',
'["sre", "four-golden-signals", "latency", "traffic", "errors", "saturation", "reliability-monitor"]',
NOW(), NOW()),

-- TypeScript union type safety
('TypeScript Union Types and Literal Types for AI System Safety',
'TypeScript literal union types (e.g., type LogComponent = "guardian" | "crag" | "core" | "system") provide compile-time guarantees that AI system components only emit logs with valid component identifiers. This prevents silent failures where a misspelled component name causes logs to be miscategorized or dropped. In MOTHER v74.8, fitness_scorer.ts used "fitness" as a LogComponent which is not in the union — TypeScript caught this at compile time (TS2345). The fix is to use "system" as the fallback component for modules not in the primary component list, or to add "fitness" to the LogComponent union type. The latter is preferable for observability: adding "fitness" to the union allows the reliability monitor to filter logs by component. Scientific basis: TypeScript Handbook "Literal Types" (Microsoft, 2024); Pierce (2002) "Types and Programming Languages" — type safety as a correctness guarantee.',
'TypeScript Handbook (Microsoft, 2024) "Literal Types"; Pierce (2002) "Types and Programming Languages" MIT Press',
'engineering',
'["typescript", "union-types", "literal-types", "type-safety", "log-component"]',
NOW(), NOW()),

-- Property-based testing exclusion from production builds
('Excluding Test Files from Production TypeScript Builds',
'Test files (*.test.ts, *.spec.ts) that import test-only dependencies (fast-check, better-sqlite3, vitest) must be excluded from the production TypeScript build configuration. The tsconfig.json root config already excluded **/*.test.ts but not **/*.spec.ts. The tsconfig.server.json did not exclude test files at all. Cloud Build uses `npx tsc --noEmit` which uses the root tsconfig.json — this includes server/**/* which includes server/mother.property.test.ts. Since fast-check and better-sqlite3 are devDependencies not installed in the production Docker image, the type check fails. Fix: add "**/*.test.ts" and "**/*.spec.ts" to the exclude array in both tsconfig.json and tsconfig.server.json. This is the standard pattern for monorepo TypeScript projects with separate test and production configs. Scientific basis: TypeScript Project References documentation (Microsoft, 2024); Jest/Vitest best practices for TypeScript.',
'TypeScript Handbook "Project References" (Microsoft, 2024); Vitest documentation "TypeScript" (2024)',
'engineering',
'["typescript", "tsconfig", "test-exclusion", "production-build", "vitest", "fast-check"]',
NOW(), NOW());
