// File: server/shms/mqtt-bridge.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

/**
 * MQTT Bridge for SHMS — Real-Time Sensor Data
 * 
 * Fix NC-004: Implementar conexão MQTT real com sensores geotécnicos
 * 
 * Referências científicas:
 * - ICOLD Bulletin 158 §4.3: Real-time monitoring requirements
 * - GISTM 2020 §8.2: Tailings dam monitoring standards
 * - Sun et al. (2025): IoT-based structural health monitoring
 * - MQTT 5.0 Specification (OASIS Standard)
 * - arXiv:2603.01022: GeoMCP — Geotechnical Monitoring Control Protocol
 */

import mqtt, { MqttClient, IClientOptions } from 'mqtt';
import { EventEmitter } from 'events';

// Tipos de dados de sensores
interface SensorReading {
  sensorId: string;
  type: 'piezometer' | 'inclinometer' | 'settlement' | 'seismic' | 'water_level';
  value: number;
  unit: string;
  timestamp: Date;
  quality: 'good' | 'uncertain' | 'bad';
  location: {
    structure: string;
    zone: string;
    depth?: number;
  };
}

interface ICOLDAlert {
  id: string;
  level: 'L1' | 'L2' | 'L3';
  sensorId: string;
  value: number;
  threshold: number;
  message: string;
  timestamp: Date;
  acknowledged: boolean;
}

// Tópicos MQTT conforme ICOLD Bulletin 158
const MQTT_TOPICS = {
  SENSOR_DATA: 'shms/sensor/+/data',      // + = sensorId wildcard
  SENSOR_STATUS: 'shms/sensor/+/status',
  ALERTS: 'shms/alert/+',
  SYSTEM_HEALTH: 'shms/system/health',
  CALIBRATION: 'shms/calibration/+',
} as const;

// Thresholds ICOLD por tipo de sensor
const ICOLD_THRESHOLDS: Record<string, { l1: number; l2: number; l3: number; unit: string }> = {
  piezometer: { l1: 1.0, l2: 2.0, l3: 3.0, unit: 'bar' },
  inclinometer: { l1: 0.5, l2: 1.0, l3: 2.0, unit: 'degrees' },
  settlement: { l1: 10, l2: 25, l3: 50, unit: 'mm' },
  seismic: { l1: 0.05, l2: 0.1, l3: 0.2, unit: 'g' },
  water_level: { l1: 0.3, l2: 0.6, l3: 0.9, unit: 'm' },
};

/**
 * MQTT Bridge para SHMS
 * Gerencia conexão com broker MQTT e processa dados de sensores em tempo real
 */
export class MQTTBridge extends EventEmitter {
  private client: MqttClient | null = null;
  private reconnectAttempts = 0;
  private readonly maxReconnectAttempts = 10;
  private readonly reconnectDelay = 5000; // 5s entre tentativas
  private isConnected = false;
  private sensorBuffer: Map<string, SensorReading[]> = new Map();
  
  constructor(
    private readonly brokerUrl: string,
    private readonly options: IClientOptions = {}
  ) {
    super();
  }
  
  /**
   * Conectar ao broker MQTT
   */
  async connect(): Promise<void> {
    return new Promise((resolve, reject) => {
      const mqttOptions: IClientOptions = {
        clientId: `mother-shms-${Date.now()}`,
        username: process.env.MQTT_USERNAME,
        password: process.env.MQTT_PASSWORD,
        keepalive: 60,
        reconnectPeriod: this.reconnectDelay,
        connectTimeout: 30000,
        will: {
          topic: 'shms/system/health',
          payload: JSON.stringify({ status: 'offline', clientId: `mother-shms-${Date.now()}` }),
          qos: 1,
          retain: true,
        },
        ...this.options,
      };
      
      console.log(`[MQTT] Connecting to ${this.brokerUrl}...`);
      this.client = mqtt.connect(this.brokerUrl, mqttOptions);
      
      this.client.on('connect', () => {
        this.isConnected = true;
        this.reconnectAttempts = 0;
        console.log('[MQTT] Connected to broker');
        
        // Subscrever a todos os tópicos SHMS
        this.subscribeToTopics();
        
        // Publicar status online
        this.publishSystemHealth('online');
        
        this.emit('connected');
        resolve();
      });
      
      this.client.on('message', (topic, message) => {
        this.handleMessage(topic, message);
      });
      
      this.client.on('error', (error) => {
        console.error('[MQTT] Connection error:', error.message);
        this.emit('error', error);
        
        if (this.reconnectAttempts === 0) {
          reject(error); // Rejeitar apenas na primeira falha
        }
      });
      
      this.client.on('close', () => {
        this.isConnected = false;
        this.reconnectAttempts++;
        
        if (this.reconnectAttempts <= this.maxReconnectAttempts) {
          console.log(`[MQTT] Disconnected. Reconnect attempt ${this.reconnectAttempts}/${this.maxReconnectAttempts}`);
          this.emit('reconnecting', this.reconnectAttempts);
        } else {
          console.error('[MQTT] Max reconnect attempts reached. Manual intervention required.');
          this.emit('max_reconnect_exceeded');
        }
      });
      
      this.client.on('reconnect', () => {
        console.log('[MQTT] Attempting reconnection...');
      });
      
      // Timeout de conexão
      setTimeout(() => {
        if (!this.isConnected) {
          reject(new Error('MQTT connection timeout after 30s'));
        }
      }, 30000);
    });
  }
  
  /**
   * Subscrever a tópicos SHMS
   */
  private subscribeToTopics(): void {
    if (!this.client) return;
    
    const topics = Object.values(MQTT_TOPICS);
    
    this.client.subscribe(topics, { qos: 1 }, (error, granted) => {
      if (error) {
        console.error('[MQTT] Subscribe error:', error);
        return;
      }
      
      console.log(`[MQTT] Subscribed to ${granted.length} topics`);
      granted.forEach(g => console.log(`  - ${g.topic} (QoS ${g.qos})`));
    });
  }
  
  /**
   * Processar mensagens recebidas
   */
  private handleMessage(topic: string, message: Buffer): void {
    try {
      const payload = JSON.parse(message.toString());
      
      if (topic.match(/^shms\/sensor\/.+\/data$/)) {
        const sensorId = topic.split('/')[2];
        this.processSensorData(sensorId, payload);
      } else if (topic.match(/^shms\/alert\/.+$/)) {
        this.processAlert(payload);
      } else if (topic === 'shms/system/health') {
        this.processSystemHealth(payload);
      }
    } catch (error) {
      console.error(`[MQTT] Failed to parse message on topic ${topic}:`, error);
    }
  }
  
  /**
   * Processar dados de sensor e verificar thresholds ICOLD
   */
  private processSensorData(sensorId: string, data: Partial<SensorReading>): void {
    const reading: SensorReading = {
      sensorId,
      type: data.type || 'piezometer',
      value: data.value || 0,
      unit: data.unit || 'unknown',
      timestamp: new Date(data.timestamp || Date.now()),
      quality: data.quality || 'good',
      location: data.location || { structure: 'unknown', zone: 'unknown' },
    };
    
    // Buffer de leituras por sensor (últimas 100)
    if (!this.sensorBuffer.has(sensorId)) {
      this.sensorBuffer.set(sensorId, []);
    }
    const buffer = this.sensorBuffer.get(sensorId)!;
    buffer.push(reading);
    if (buffer.length > 100) buffer.shift();
    
    // Emitir evento de nova leitura
    this.emit('sensor_data', reading);
    
    // Verificar thresholds ICOLD
    this.checkICOLDThresholds(reading);
  }
  
  /**
   * Verificar thresholds ICOLD e gerar alertas
   * Referência: ICOLD Bulletin 158 §4.3
   */
  private checkICOLDThresholds(reading: SensorReading): void {
    const thresholds = ICOLD_THRESHOLDS[reading.type];
    if (!thresholds) return;
    
    let alertLevel: 'L1' | 'L2' | 'L3' | null = null;
    
    if (reading.value >= thresholds.l3) {
      alertLevel = 'L3'; // EMERGÊNCIA
    } else if (reading.value >= thresholds.l2) {
      alertLevel = 'L2'; // ALERTA
    } else if (reading.value >= thresholds.l1) {
      alertLevel = 'L1'; // ATENÇÃO
    }
    
    if (alertLevel) {
      const alert: ICOLDAlert = {
        id: `alert-${Date.now()}-${reading.sensorId}`,
        level: alertLevel,
        sensorId: reading.sensorId,
        value: reading.value,
        threshold: thresholds[alertLevel.toLowerCase() as 'l1' | 'l2' | 'l3'],
        message: `Sensor ${reading.sensorId}: ${reading.type} = ${reading.value}${thresholds.unit} (${alertLevel})`,
        timestamp: reading.timestamp,
        acknowledged: false,
      };
      
      console.warn(`[MQTT] ICOLD ${alertLevel} Alert: ${alert.message}`);
      this.emit('icold_alert', alert);
      
      // Publicar alerta de volta ao broker
      this.publishAlert(alert);
    }
  }
  
  /**
   * Publicar alerta no broker MQTT
   */
  private publishAlert(alert: ICOLDAlert): void {
    if (!this.client || !this.isConnected) return;
    
    const topic = `shms/alert/${alert.sensorId}`;
    this.client.publish(topic, JSON.stringify(alert), { qos: 2, retain: true });
  }
  
  /**
   * Publicar status de saúde do sistema
   */
  private publishSystemHealth(status: 'online' | 'offline'): void {
    if (!this.client) return;
    
    const health = {
      status,
      clientId: this.client.options.clientId,
      timestamp: new Date().toISOString(),
      sensorsConnected: this.sensorBuffer.size,
      version: 'v82.4',
    };
    
    this.client.publish('shms/system/health', JSON.stringify(health), { 
      qos: 1, 
      retain: true 
    });
  }
  
  /**
   * Processar status de saúde do sistema
   */
  private processSystemHealth(data: unknown): void {
    this.emit('system_health', data);
  }
  
  /**
   * Processar alertas recebidos
   */
  private processAlert(data: unknown): void {
    this.emit('alert_received', data);
  }
  
  /**
   * Obter leituras recentes de um sensor
   */
  getSensorReadings(sensorId: string, count = 10): SensorReading[] {
    const buffer = this.sensorBuffer.get(sensorId) || [];
    return buffer.slice(-count);
  }
  
  /**
   * Verificar status da conexão
   */
  getStatus(): { connected: boolean; reconnectAttempts: number; sensorsTracked: number } {
    return {
      connected: this.isConnected,
      reconnectAttempts: this.reconnectAttempts,
      sensorsTracked: this.sensorBuffer.size,
    };
  }
  
  /**
   * Desconectar graciosamente
   */
  async disconnect(): Promise<void> {
    if (!this.client) return;
    
    this.publishSystemHealth('offline');
    
    return new Promise((resolve) => {
      this.client!.end(false, {}, () => {
        this.isConnected = false;
        console.log('[MQTT] Disconnected gracefully');
        resolve();
      });
    });
  }
}

// Singleton para uso global
let mqttBridgeInstance: MQTTBridge | null = null;

/**
 * Obter instância singleton do MQTT Bridge
 */
export function getMQTTBridge(): MQTTBridge {
  if (!mqttBridgeInstance) {
    const brokerUrl = process.env.MQTT_BROKER_URL || 'mqtt://localhost:1883';
    mqttBridgeInstance = new MQTTBridge(brokerUrl);
  }
  return mqttBridgeInstance;
}

/**
 * Inicializar MQTT Bridge na startup do servidor
 * Adicionar ao server/_core/production-entry.ts:
 * 
 * import { getMQTTBridge } from '../shms/mqtt-bridge';
 * 
 * // Inicializar MQTT na startup
 * const mqttBridge = getMQTTBridge();
 * mqttBridge.connect()
 *   .then(() => console.log('[SHMS] MQTT Bridge connected'))
 *   .catch(err => console.error('[SHMS] MQTT Bridge failed:', err));
 * 
 * mqttBridge.on('icold_alert', (alert) => {
 *   // Notificar MOTHER para análise
 *   motherCore.processAlert(alert);
 * });
 */
export { SensorReading, ICOLDAlert, MQTT_TOPICS, ICOLD_THRESHOLDS };
