// File: server/_core/production-entry.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

// ANTES (NC-001 — VULNERÁVEL):
// app.use(cors({ origin: '*' }));
// res.setHeader('Access-Control-Allow-Origin', '*');

// DEPOIS (Fix NC-001):
import { corsConfig } from './cors-config';
app.use(corsConfig);

// Remover todos os setHeader('Access-Control-Allow-Origin', '*') inline
// Buscar e substituir: grep -r "Access-Control-Allow-Origin.*\*" server/
