// File: server/_core/rate-limiter.ts
// Fix NC-006 | OWASP API Security Top 10 2023 API4
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit
// Protocolo Delphi + MAD — 3 Rodadas | Ciclo 194 | 2026-03-08
// NC-INFRA-005 FIX (Sprint 10 C209): Redis-backed distributed rate limiter implemented
// in server/_core/rate-limiter-redis.ts (createDistributedRateLimiter).
// This file (rate-limiter.ts) is MAINTAINED for backward compatibility with existing imports.
// For new Cloud Run deployments, use createDistributedRateLimiter() from rate-limiter-redis.ts.
// Scientific basis: OWASP API4:2023 + Google Cloud Run docs (2024) + Kleppmann (2017) §9.4.
// NOTE: This file still uses MemoryStore — production deployments should migrate to
// rate-limiter-redis.ts with REDIS_URL set in Cloud Run environment variables.

import { Request, Response, NextFunction } from 'express';
import rateLimit from 'express-rate-limit';

// Limiter por IP: 100 req/min (OWASP recomendação)
const ipLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 100,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many requests from this IP', code: 'RATE_LIMIT_IP', retryAfter: 60 },
  skip: (req: Request) => req.path === '/health' || req.path === '/status',
});

// Limiter por API Key: 1000 req/min
const apiKeyLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 1000,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'API key rate limit exceeded', code: 'RATE_LIMIT_KEY', retryAfter: 60 },
  keyGenerator: (req: Request) => req.headers['x-api-key'] as string,
});

// Middleware combinado: aplica limiter correto
export function apiRateLimiter(req: Request, res: Response, next: NextFunction): void {
  const hasApiKey = req.headers['x-api-key'] && typeof req.headers['x-api-key'] === 'string';
  if (hasApiKey) {
    apiKeyLimiter(req, res, next);
  } else {
    ipLimiter(req, res, next);
  }
}

// Limiter estrito para endpoints de autenticação: 5 req/15min
export const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 5,
  standardHeaders: true,
  message: { error: 'Too many auth attempts', code: 'RATE_LIMIT_AUTH' },
});
