// File: server/_core/structured-logger.ts
// Fix NC-007 | OpenTelemetry CNCF 2023 | Google SRE Book
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit
// Protocolo Delphi + MAD — 3 Rodadas | Ciclo 194 | 2026-03-08
// Substitui 550 console.log por logger estruturado

import { randomUUID } from 'crypto';
import { Request, Response, NextFunction } from 'express';

// Simplified structured logger (no pino dependency required)
// In production: replace with: import pino from 'pino';
const SENSITIVE_KEYS = ['password', 'token', 'authorization', 'apiKey', 'secret', 'x-api-key'];

function sanitize(obj: Record<string, unknown>): Record<string, unknown> {
  const result = { ...obj };
  for (const key of SENSITIVE_KEYS) {
    if (key in result) result[key] = '[REDACTED]';
  }
  return result;
}

function formatLog(level: string, msg: string, ctx?: object): string {
  return JSON.stringify({
    level,
    time: new Date().toISOString(),
    service: 'mother-cognitive-core',
    version: 'v82.4',
    message: msg,
    ...(ctx ? sanitize(ctx as Record<string, unknown>) : {}),
  });
}

export const logger = {
  debug: (ctx: object | string, msg?: string) => {
    if (process.env.LOG_LEVEL === 'debug') {
      console.debug(typeof ctx === 'string' ? formatLog('debug', ctx) : formatLog('debug', msg || '', ctx));
    }
  },
  info: (ctx: object | string, msg?: string) => {
    console.info(typeof ctx === 'string' ? formatLog('info', ctx) : formatLog('info', msg || '', ctx));
  },
  warn: (ctx: object | string, msg?: string) => {
    console.warn(typeof ctx === 'string' ? formatLog('warn', ctx) : formatLog('warn', msg || '', ctx));
  },
  error: (ctx: object | string, msg?: string) => {
    console.error(typeof ctx === 'string' ? formatLog('error', ctx) : formatLog('error', msg || '', ctx));
  },
};

// Middleware: adiciona requestId a cada requisição
export function requestLogger(req: Request, res: Response, next: NextFunction): void {
  const requestId = (req.headers['x-request-id'] as string) || randomUUID();
  res.setHeader('X-Request-ID', requestId);

  const start = Date.now();
  res.on('finish', () => {
    logger.info({
      requestId,
      method: req.method,
      path: req.path,
      status: res.statusCode,
      duration: Date.now() - start,
      ip: req.ip,
    }, 'HTTP request');
  });

  next();
}

// Helper para migração: substitui console.log existentes
export const log = {
  debug: (msg: string, ctx?: object) => logger.debug(ctx || {}, msg),
  info: (msg: string, ctx?: object) => logger.info(ctx || {}, msg),
  warn: (msg: string, ctx?: object) => logger.warn(ctx || {}, msg),
  error: (msg: string, ctx?: object) => logger.error(ctx || {}, msg),
};
