// File: server/dgm/dgm-cycle3.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

/**
 * DGM Cycle 3 — Darwin Gödel Machine Autonomous Cycle
 * 
 * Fix NC-003: Adicionar MCC (Minimum Criterion Convergence) stopping criterion
 * e cooldown de 24h entre ciclos para evitar loop infinito
 * 
 * Referências científicas:
 * - arXiv:2505.22954 — Darwin Gödel Machine: Self-Improving AI
 * - HELM arXiv:2211.09110 — Holistic Evaluation of Language Models
 * - MCC Stopping Criterion: Cohen (1988) Statistical Power Analysis
 * - Google SRE Book (2016): Error Budget and SLOs
 */

import { Octokit } from '@octokit/rest';
import { createHash } from 'crypto';

// Constantes do ciclo DGM
const MAX_PROPOSALS_PER_CYCLE = 3;
const COOLDOWN_HOURS = 24;
const MCC_THRESHOLD = 0.85; // Minimum Criterion Convergence
const MAX_RETRIES = 3;
const PROPOSAL_SIMILARITY_THRESHOLD = 0.90; // Propostas com >90% similaridade = duplicata

interface DGMProposal {
  id: string;
  summary: string;
  targetFile: string;
  changeType: 'fix' | 'feature' | 'refactor' | 'test';
  priority: 'critical' | 'high' | 'medium' | 'low';
  estimatedImpact: number; // 0-1
  hash: string; // Para deduplicação
  createdAt: Date;
}

interface DGMCycleState {
  lastCycleAt: Date | null;
  proposalsThisCycle: number;
  totalProposals: number;
  convergenceScore: number;
  cycleHistory: Array<{ date: Date; proposals: number; merged: number }>;
}

// Estado persistido em memória (em produção: usar Redis/DB)
let cycleState: DGMCycleState = {
  lastCycleAt: null,
  proposalsThisCycle: 0,
  totalProposals: 0,
  convergenceScore: 0,
  cycleHistory: [],
};

/**
 * Calcula hash de uma proposta para deduplicação
 */
function hashProposal(proposal: Omit<DGMProposal, 'hash' | 'id' | 'createdAt'>): string {
  const content = `${proposal.targetFile}:${proposal.changeType}:${proposal.summary}`;
  return createHash('sha256').update(content).digest('hex').substring(0, 16);
}

/**
 * Verifica se o cooldown entre ciclos foi respeitado
 * Referência: Google SRE Book (2016) — Error Budget
 */
function isCooldownActive(): boolean {
  if (!cycleState.lastCycleAt) return false;
  
  const hoursSinceLastCycle = 
    (Date.now() - cycleState.lastCycleAt.getTime()) / (1000 * 60 * 60);
  
  return hoursSinceLastCycle < COOLDOWN_HOURS;
}

/**
 * Calcula o score de convergência MCC
 * Referência: HELM arXiv:2211.09110 — Benchmark Saturation
 */
function calculateConvergenceScore(proposals: DGMProposal[]): number {
  if (proposals.length === 0) return 0;
  
  // Score baseado em: diversidade de tipos, impacto estimado, prioridade
  const typeDistribution = new Set(proposals.map(p => p.changeType)).size / 4; // 4 tipos possíveis
  const avgImpact = proposals.reduce((sum, p) => sum + p.estimatedImpact, 0) / proposals.length;
  const hasCritical = proposals.some(p => p.priority === 'critical') ? 1 : 0;
  
  // Fórmula MCC: média ponderada
  return (typeDistribution * 0.3) + (avgImpact * 0.5) + (hasCritical * 0.2);
}

/**
 * Verifica se uma proposta é duplicata de propostas recentes
 */
async function isDuplicateProposal(
  proposal: DGMProposal,
  recentProposals: DGMProposal[]
): Promise<boolean> {
  return recentProposals.some(recent => {
    // Verificar hash exato
    if (recent.hash === proposal.hash) return true;
    
    // Verificar similaridade de arquivo + tipo
    if (recent.targetFile === proposal.targetFile && 
        recent.changeType === proposal.changeType) {
      return true;
    }
    
    return false;
  });
}

/**
 * Gera propostas de melhoria baseadas no estado atual do sistema
 * Substitui o gerador anterior que criava propostas infinitas
 */
async function generateProposals(
  recentProposals: DGMProposal[]
): Promise<DGMProposal[]> {
  // Lista de melhorias prioritárias conhecidas (em produção: geradas por LLM)
  const candidateProposals: Omit<DGMProposal, 'hash' | 'id' | 'createdAt'>[] = [
    {
      summary: 'Add Zod validation to A2A endpoints',
      targetFile: 'server/mother/a2a-server.ts',
      changeType: 'fix',
      priority: 'high',
      estimatedImpact: 0.8,
    },
    {
      summary: 'Implement rate limiting middleware',
      targetFile: 'server/_core/rate-limiter.ts',
      changeType: 'feature',
      priority: 'high',
      estimatedImpact: 0.75,
    },
    {
      summary: 'Replace console.log with structured logging',
      targetFile: 'server/_core/logger.ts',
      changeType: 'refactor',
      priority: 'medium',
      estimatedImpact: 0.6,
    },
  ];
  
  const proposals: DGMProposal[] = [];
  
  for (const candidate of candidateProposals) {
    if (proposals.length >= MAX_PROPOSALS_PER_CYCLE) break;
    
    const hash = hashProposal(candidate);
    const proposal: DGMProposal = {
      ...candidate,
      id: `dgm-${Date.now()}-${hash}`,
      hash,
      createdAt: new Date(),
    };
    
    // Verificar duplicata antes de adicionar
    const isDuplicate = await isDuplicateProposal(proposal, recentProposals);
    if (!isDuplicate) {
      proposals.push(proposal);
    } else {
      console.log(`[DGM] Skipping duplicate proposal: ${proposal.summary}`);
    }
  }
  
  return proposals;
}

/**
 * Cria Pull Request no GitHub para uma proposta
 */
async function createPullRequest(
  octokit: Octokit,
  proposal: DGMProposal,
  owner: string,
  repo: string
): Promise<{ prNumber: number; url: string }> {
  const branchName = `dgm/auto-${proposal.changeType}-${proposal.hash}`;
  
  // Verificar se branch já existe
  try {
    await octokit.repos.getBranch({ owner, repo, branch: branchName });
    console.log(`[DGM] Branch ${branchName} already exists, skipping`);
    return { prNumber: 0, url: '' };
  } catch {
    // Branch não existe, criar
  }
  
  // Obter SHA do branch principal
  const { data: mainBranch } = await octokit.repos.getBranch({
    owner, repo, branch: 'main',
  });
  
  // Criar branch
  await octokit.git.createRef({
    owner, repo,
    ref: `refs/heads/${branchName}`,
    sha: mainBranch.commit.sha,
  });
  
  // Criar PR
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[DGM Auto] ${proposal.summary}`,
    body: `## DGM Autonomous Proposal\n\n**Type:** ${proposal.changeType}\n**Priority:** ${proposal.priority}\n**Impact:** ${(proposal.estimatedImpact * 100).toFixed(0)}%\n\n### Description\n${proposal.summary}\n\n### Scientific Basis\n- Darwin Gödel Machine (arXiv:2505.22954)\n- MCC Stopping Criterion (HELM arXiv:2211.09110)\n\n*Generated by DGM Cycle 3 — MOTHER v82.4*`,
    head: branchName,
    base: 'main',
    draft: true, // PR como rascunho para revisão humana
  });
  
  return { prNumber: pr.number, url: pr.html_url };
}

/**
 * Ciclo principal do DGM
 * Executa com cooldown e critério de convergência MCC
 */
export async function runDGMCycle(): Promise<{
  executed: boolean;
  reason?: string;
  proposals?: number;
  convergenceScore?: number;
}> {
  console.log('[DGM] Starting cycle check...');
  
  // 1. Verificar cooldown
  if (isCooldownActive()) {
    const hoursRemaining = COOLDOWN_HOURS - 
      (Date.now() - cycleState.lastCycleAt!.getTime()) / (1000 * 60 * 60);
    
    console.log(`[DGM] Cooldown active. ${hoursRemaining.toFixed(1)}h remaining.`);
    return { 
      executed: false, 
      reason: `Cooldown active: ${hoursRemaining.toFixed(1)}h remaining` 
    };
  }
  
  // 2. Verificar limite de propostas por ciclo
  if (cycleState.proposalsThisCycle >= MAX_PROPOSALS_PER_CYCLE) {
    console.log('[DGM] Max proposals per cycle reached. Resetting for next cycle.');
    cycleState.proposalsThisCycle = 0;
    return { 
      executed: false, 
      reason: 'Max proposals per cycle reached' 
    };
  }
  
  // 3. Obter propostas recentes (últimas 24h) para deduplicação
  const recentProposals: DGMProposal[] = []; // Em produção: buscar do BD
  
  // 4. Gerar novas propostas
  const proposals = await generateProposals(recentProposals);
  
  if (proposals.length === 0) {
    console.log('[DGM] No new proposals generated. System may be converging.');
    cycleState.convergenceScore = Math.min(1.0, cycleState.convergenceScore + 0.1);
    return { 
      executed: false, 
      reason: 'No new proposals — system converging',
      convergenceScore: cycleState.convergenceScore,
    };
  }
  
  // 5. Calcular score MCC
  const convergenceScore = calculateConvergenceScore(proposals);
  
  if (convergenceScore < MCC_THRESHOLD) {
    console.log(`[DGM] Convergence score ${convergenceScore.toFixed(2)} below threshold ${MCC_THRESHOLD}`);
    return { 
      executed: false, 
      reason: `MCC score ${convergenceScore.toFixed(2)} < threshold ${MCC_THRESHOLD}`,
      convergenceScore,
    };
  }
  
  // 6. Executar propostas (criar PRs)
  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) {
    console.error('[DGM] GITHUB_TOKEN not configured');
    return { executed: false, reason: 'GITHUB_TOKEN not configured' };
  }
  
  const octokit = new Octokit({ auth: githubToken });
  let createdPRs = 0;
  
  for (const proposal of proposals) {
    try {
      const result = await createPullRequest(
        octokit, proposal, 'Ehrvi', 'mother-v7-improvements'
      );
      
      if (result.prNumber > 0) {
        console.log(`[DGM] Created PR #${result.prNumber}: ${result.url}`);
        createdPRs++;
      }
    } catch (error) {
      console.error(`[DGM] Failed to create PR for: ${proposal.summary}`, error);
    }
  }
  
  // 7. Atualizar estado do ciclo
  cycleState.lastCycleAt = new Date();
  cycleState.proposalsThisCycle += proposals.length;
  cycleState.totalProposals += proposals.length;
  cycleState.convergenceScore = convergenceScore;
  cycleState.cycleHistory.push({
    date: new Date(),
    proposals: proposals.length,
    merged: 0, // Atualizar quando PRs forem mergeados
  });
  
  console.log(`[DGM] Cycle complete. Created ${createdPRs} PRs. Convergence: ${convergenceScore.toFixed(2)}`);
  
  return {
    executed: true,
    proposals: createdPRs,
    convergenceScore,
  };
}

/**
 * Scheduler do DGM — executar a cada 24h via cron
 * Adicionar ao server/_core/production-entry.ts:
 * 
 * import cron from 'node-cron';
 * import { runDGMCycle } from '../dgm/dgm-cycle3';
 * 
 * // DGM: executar diariamente às 03:00 UTC
 * cron.schedule('0 3 * * *', async () => {
 *   const result = await runDGMCycle();
 *   console.log('[DGM Cron]', result);
 * });
 */
export { cycleState, DGMProposal, DGMCycleState };
