// File: server/mother/__tests__/core.test.ts
// Generated by Conselho dos 6 IAs — MOTHER v82.4 Audit

/**
 * Tests for MOTHER Core Module
 * 
 * Referências:
 * - IEEE 1028-2008: Software Reviews and Audits
 * - ISTQB: Test Design Techniques
 * - Vitest Documentation: https://vitest.dev
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Mock de dependências externas ANTES de importar o módulo
vi.mock('../../services/database', () => ({
  db: {
    query: vi.fn(),
    execute: vi.fn(),
  },
}));

vi.mock('../../services/llm', () => ({
  callLLM: vi.fn(),
  callLLMStream: vi.fn(),
}));

vi.mock('../../services/embedding', () => ({
  generateEmbedding: vi.fn().mockResolvedValue(new Array(1536).fill(0.1)),
  similaritySearch: vi.fn().mockResolvedValue([]),
}));

// Importar após mocks
import { db } from '../../services/database';
import { callLLM } from '../../services/llm';

// Tipos para testes
interface QueryResult {
  response: string;
  sources: string[];
  confidence: number;
  processingTime: number;
}

interface KnowledgeRecord {
  id: string;
  content: string;
  source: string;
  category: string;
  embedding?: number[];
}

// Mock do módulo core (adaptar ao export real do core.ts)
const mockCoreModule = {
  processQuery: vi.fn(),
  updateMemory: vi.fn(),
  getKnowledge: vi.fn(),
  getVersion: vi.fn().mockReturnValue('v82.4'),
};

describe('MOTHER Core — processQuery()', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    
    // Setup padrão: LLM retorna resposta válida
    (callLLM as ReturnType<typeof vi.fn>).mockResolvedValue({
      content: 'Resposta de teste sobre ICOLD Bulletin 158',
      tokens: 150,
      model: 'claude-opus-4-5',
    });
    
    // Setup padrão: DB retorna conhecimento relevante
    (db.query as ReturnType<typeof vi.fn>).mockResolvedValue([
      {
        id: 'k001',
        content: 'ICOLD Bulletin 158: Monitoramento de barragens',
        source: 'ICOLD',
        category: 'shms',
        relevance: 0.92,
      },
    ]);
  });

  it('deve retornar resposta válida para query simples', async () => {
    const query = 'O que é ICOLD Bulletin 158?';
    const result: QueryResult = await mockCoreModule.processQuery(query);
    
    expect(result).toBeDefined();
    expect(result.response).toBeTruthy();
    expect(result.confidence).toBeGreaterThan(0);
    expect(result.processingTime).toBeGreaterThan(0);
  });

  it('deve incluir fontes nas respostas', async () => {
    mockCoreModule.processQuery.mockResolvedValue({
      response: 'ICOLD Bulletin 158 define padrões de monitoramento',
      sources: ['ICOLD Bulletin 158', 'GISTM 2020'],
      confidence: 0.89,
      processingTime: 1200,
    });
    
    const result = await mockCoreModule.processQuery('ICOLD standards');
    expect(result.sources).toHaveLength(2);
    expect(result.sources).toContain('ICOLD Bulletin 158');
  });

  it('deve lidar com query vazia graciosamente', async () => {
    mockCoreModule.processQuery.mockRejectedValue(new Error('Query cannot be empty'));
    
    await expect(mockCoreModule.processQuery('')).rejects.toThrow('Query cannot be empty');
  });

  it('deve retornar resposta em menos de 30 segundos (SLA)', async () => {
    const startTime = Date.now();
    mockCoreModule.processQuery.mockResolvedValue({
      response: 'Resposta rápida',
      sources: [],
      confidence: 0.75,
      processingTime: 2500,
    });
    
    const result = await mockCoreModule.processQuery('test query');
    const elapsed = Date.now() - startTime;
    
    expect(elapsed).toBeLessThan(30000); // SLA: 30s
    expect(result.processingTime).toBeLessThan(30000);
  });

  it('deve usar cache para queries repetidas', async () => {
    const query = 'cached query test';
    
    mockCoreModule.processQuery
      .mockResolvedValueOnce({ response: 'First call', sources: [], confidence: 0.9, processingTime: 2000 })
      .mockResolvedValueOnce({ response: 'Cached call', sources: [], confidence: 0.9, processingTime: 50 });
    
    const result1 = await mockCoreModule.processQuery(query);
    const result2 = await mockCoreModule.processQuery(query);
    
    // Segunda chamada deve ser mais rápida (cache)
    expect(result2.processingTime).toBeLessThan(result1.processingTime);
  });
});

describe('MOTHER Core — updateMemory()', () => {
  it('deve persistir novo conhecimento no BD', async () => {
    const newKnowledge: KnowledgeRecord = {
      id: 'test-001',
      content: 'Novo conhecimento sobre SHMS',
      source: 'arXiv:2603.01022',
      category: 'shms',
    };
    
    mockCoreModule.updateMemory.mockResolvedValue({ success: true, id: 'test-001' });
    
    const result = await mockCoreModule.updateMemory(newKnowledge);
    expect(result.success).toBe(true);
    expect(result.id).toBe('test-001');
  });

  it('deve rejeitar conhecimento sem source', async () => {
    const invalidKnowledge = { id: 'bad-001', content: 'Sem source', category: 'test' };
    mockCoreModule.updateMemory.mockRejectedValue(new Error('Source is required'));
    
    await expect(mockCoreModule.updateMemory(invalidKnowledge)).rejects.toThrow('Source is required');
  });

  it('deve gerar embedding para novo conhecimento', async () => {
    const knowledge: KnowledgeRecord = {
      id: 'embed-001',
      content: 'Conhecimento para embedding',
      source: 'test',
      category: 'test',
    };
    
    mockCoreModule.updateMemory.mockResolvedValue({
      success: true,
      id: 'embed-001',
      embeddingGenerated: true,
    });
    
    const result = await mockCoreModule.updateMemory(knowledge);
    expect(result.embeddingGenerated).toBe(true);
  });
});

describe('MOTHER Core — getKnowledge()', () => {
  it('deve retornar conhecimento por categoria', async () => {
    mockCoreModule.getKnowledge.mockResolvedValue([
      { id: 'k001', content: 'SHMS knowledge 1', category: 'shms', source: 'ICOLD' },
      { id: 'k002', content: 'SHMS knowledge 2', category: 'shms', source: 'GISTM' },
    ]);
    
    const results = await mockCoreModule.getKnowledge({ category: 'shms' });
    expect(results).toHaveLength(2);
    expect(results[0].category).toBe('shms');
  });

  it('deve retornar array vazio para categoria inexistente', async () => {
    mockCoreModule.getKnowledge.mockResolvedValue([]);
    
    const results = await mockCoreModule.getKnowledge({ category: 'nonexistent' });
    expect(results).toHaveLength(0);
  });

  it('deve suportar busca por similaridade semântica', async () => {
    mockCoreModule.getKnowledge.mockResolvedValue([
      { id: 'k001', content: 'ICOLD monitoring standards', similarity: 0.94 },
      { id: 'k002', content: 'Dam safety protocols', similarity: 0.87 },
    ]);
    
    const results = await mockCoreModule.getKnowledge({ 
      query: 'dam monitoring',
      topK: 2,
    });
    
    expect(results).toHaveLength(2);
    expect(results[0].similarity).toBeGreaterThan(results[1].similarity);
  });
});

describe('MOTHER Core — getVersion()', () => {
  it('deve retornar versão atual', () => {
    const version = mockCoreModule.getVersion();
    expect(version).toMatch(/^v\d+\.\d+/);
    expect(version).toBe('v82.4');
  });
});
