/**
 * connection-registry.ts — MOTHER v81.8 — Ciclo 189
 *
 * Registry of all modules generated by DGM and their connection status.
 * Implements R27: Every new DGM module MUST be registered here with status CONNECTED or ORPHAN.
 * Modules with ORPHAN status for more than 2 cycles must be connected or archived.
 *
 * Scientific basis:
 * - Conselho dos 6 IAs C188 — diagnóstico unânime "Síndrome do Código Orphan"
 * - Lehman (1980) — "Programs, Life Cycles, and Laws of Software Evolution" — IEEE
 *   Lei de Lehman: sistemas E-type crescem em complexidade sem intervenção ativa.
 * - CMMI Level 3 (Defined) — requires documented process for module lifecycle management
 *
 * @module connection-registry
 * @version 1.0.0
 * @cycle C189
 * @rule R27
 */

export type ModuleStatus = 'CONNECTED' | 'ORPHAN' | 'ARCHIVED' | 'DEPRECATED';

export interface ModuleRegistration {
  name: string;
  path: string;
  exportedFunction: string;
  importTarget: string;
  status: ModuleStatus;
  cycleCreated: number;
  cycleConnected?: number;
  cycleArchived?: number;
  description: string;
  priority: 'P0' | 'P1' | 'P2' | 'LOW';
  councilDecision?: string;
}

/**
 * Central registry of all DGM-generated modules and their connection status.
 * Updated every cycle by the maintenance agent.
 * Last updated: Ciclo 189 (2026-03-08)
 */
export const CONNECTION_REGISTRY: ModuleRegistration[] = [
  // ============================================================
  // CONNECTED — Active in production pipeline
  // ============================================================
  {
    name: 'agentic-learning',
    path: 'server/mother/agentic-learning.ts',
    exportedFunction: 'agenticLearn',
    importTarget: 'server/mother/dgm-orchestrator.ts',
    status: 'CONNECTED',
    cycleCreated: 140,
    cycleConnected: 140,
    description: 'Agentic learning — guides and examples for DGM',
    priority: 'P0',
  },
  {
    name: 'self-improve',
    path: 'server/mother/self-improve.ts',
    exportedFunction: 'selfImprove',
    importTarget: 'server/mother/core.ts',
    status: 'CONNECTED',
    cycleCreated: 120,
    cycleConnected: 120,
    description: 'Self-improvement via reflection',
    priority: 'P0',
  },
  {
    name: 'dgm-orchestrator',
    path: 'server/mother/dgm-orchestrator.ts',
    exportedFunction: 'DGMOrchestrator',
    importTarget: 'server/mother/dgm-agent.ts',
    status: 'CONNECTED',
    cycleCreated: 150,
    cycleConnected: 150,
    description: 'DGM Sprint 9 orchestrator with triggerDeploy (C189)',
    priority: 'P0',
    councilDecision: 'C188 NC-DGM-001 RESOLVED C189',
  },
  {
    name: 'knowledge',
    path: 'server/mother/knowledge.ts',
    exportedFunction: 'queryKnowledge',
    importTarget: 'server/mother/core.ts',
    status: 'CONNECTED',
    cycleCreated: 100,
    cycleConnected: 100,
    description: 'Knowledge retrieval with HippoRAG2 as Source 5 (C189)',
    priority: 'P0',
    councilDecision: 'C188 NC-LEARN-001 RESOLVED C189',
  },
  {
    name: 'learning',
    path: 'server/mother/learning.ts',
    exportedFunction: 'processLearning',
    importTarget: 'server/mother/core.ts',
    status: 'CONNECTED',
    cycleCreated: 100,
    cycleConnected: 100,
    description: 'Learning hub with memory_agent importance scoring (C189)',
    priority: 'P0',
    councilDecision: 'C188 NC-LEARN-001 RESOLVED C189',
  },
  {
    name: 'memory_agent',
    path: 'server/mother/memory_agent.ts',
    exportedFunction: 'computeImportanceScore',
    importTarget: 'server/mother/learning.ts',
    status: 'CONNECTED',
    cycleCreated: 170,
    cycleConnected: 189,
    description: 'Episodic memory consolidation with importance scoring',
    priority: 'P0',
    councilDecision: 'C188 NC-LEARN-001 RESOLVED C189',
  },
  {
    name: 'hipporag2',
    path: 'server/mother/hipporag2.ts',
    exportedFunction: 'hippoRAG2Retrieve',
    importTarget: 'server/mother/knowledge.ts',
    status: 'CONNECTED',
    cycleCreated: 180,
    cycleConnected: 189,
    description: 'HippoRAG2 hierarchical knowledge graph retrieval',
    priority: 'P0',
    councilDecision: 'C188 NC-LEARN-001 RESOLVED C189',
  },
  {
    name: 'active-study',
    path: 'server/mother/active-study.ts',
    exportedFunction: 'triggerActiveStudy',
    importTarget: 'server/mother/core.ts',
    status: 'CONNECTED',
    cycleCreated: 160,
    cycleConnected: 160,
    description: 'Active academic study trigger (Semantic Scholar + arXiv)',
    priority: 'P1',
  },
  {
    name: 'shms-analyze-endpoint',
    path: 'server/mother/shms-analyze-endpoint.ts',
    exportedFunction: 'handleShmsAnalyze',
    importTarget: 'server/mother/a2a-server.ts',
    status: 'CONNECTED',
    cycleCreated: 182,
    cycleConnected: 182,
    description: 'SHMS v2 analysis endpoint with G-Eval geotechnical calibration',
    priority: 'P0',
  },
  {
    name: 'sensor-validator',
    path: 'server/shms/sensor-validator.ts',
    exportedFunction: 'validateSensorReading',
    importTarget: 'server/shms/shms-api.ts',
    status: 'CONNECTED',
    cycleCreated: 189,
    cycleConnected: 189,
    description: 'GISTM+ICOLD sensor reading validation — NC-SHMS-001 resolution',
    priority: 'P0',
    councilDecision: 'C188 NC-SHMS-001 RESOLVED C189',
  },

  // ============================================================
  // ORPHAN — Written but not connected (P0 = must connect this cycle)
  // ============================================================
  {
    name: 'lora-trainer',
    path: 'server/mother/lora-trainer.ts',
    exportedFunction: 'LoraTrainer',
    importTarget: 'server/mother/dgm-orchestrator.ts',
    status: 'ORPHAN',
    cycleCreated: 115,
    description: 'LoRA fine-tuning — CRITICAL: only way for MOTHER to learn persistently',
    priority: 'P0',
    councilDecision: 'C188 Seção 3.2.1 — P0 CRITICAL — connect in C190',
  },
  {
    name: 'shms-geval-geotechnical',
    path: 'server/mother/shms-geval-geotechnical.ts',
    exportedFunction: 'evaluateGeotechnicalResponse',
    importTarget: 'server/mother/shms-analyze-endpoint.ts',
    status: 'CONNECTED',
    cycleCreated: 187,
    cycleConnected: 189,
    description: 'G-Eval calibrated for geotechnical responses',
    priority: 'P0',
    councilDecision: 'C188 Seção 7.2 — RESOLVED C189 (already imported)',
  },
  {
    name: 'finetuning-pipeline',
    path: 'server/mother/finetuning-pipeline.ts',
    exportedFunction: 'FineTuningPipeline',
    importTarget: 'server/mother/lora-trainer.ts',
    status: 'ORPHAN',
    cycleCreated: 118,
    description: 'Fine-tuning pipeline preparation for LoRA',
    priority: 'P1',
    councilDecision: 'C188 Seção 3.1 — P1 — connect after lora-trainer',
  },

  // ============================================================
  // ARCHIVED — Superseded by newer implementations
  // ============================================================
  {
    name: 'dgm-sprint8-autonomous',
    path: 'server/mother/dgm-sprint8-autonomous.ts',
    exportedFunction: 'N/A',
    importTarget: 'N/A',
    status: 'ARCHIVED',
    cycleCreated: 145,
    cycleArchived: 189,
    description: 'Sprint 8 — superseded by Sprint 9 (dgm-orchestrator.ts)',
    priority: 'LOW',
    councilDecision: 'C188 Seção 3.1 — Archive',
  },
  {
    name: 'dgm-cycle8-additions',
    path: 'server/mother/dgm-cycle8-additions.ts',
    exportedFunction: 'N/A',
    importTarget: 'N/A',
    status: 'ARCHIVED',
    cycleCreated: 145,
    cycleArchived: 189,
    description: 'Sprint 8 additions — superseded by Sprint 9',
    priority: 'LOW',
    councilDecision: 'C188 Seção 3.1 — Archive',
  },

  // ============================================================
  // DEPRECATED — SHMS v1 (will be removed in C195)
  // ============================================================
  {
    name: 'shms-api-v1',
    path: 'server/shms/shms-api.ts',
    exportedFunction: 'registerSHMSRoutes',
    importTarget: 'server/mother/a2a-server.ts',
    status: 'DEPRECATED',
    cycleCreated: 109,
    description: 'SHMS v1 — deprecated in C189, removal planned C195',
    priority: 'LOW',
    councilDecision: 'C188 NC-ARCH-001 — DEPRECATED C189, remove C195',
  },
];

/**
 * Returns all modules with ORPHAN status.
 * Used by DGM orchestrator to identify modules needing connection.
 */
export function getOrphanModules(): ModuleRegistration[] {
  return CONNECTION_REGISTRY.filter(m => m.status === 'ORPHAN');
}

/**
 * Returns modules that have been ORPHAN for more than 2 cycles.
 * These MUST be connected or archived per R27.
 * @param currentCycle - The current cycle number
 */
export function getCriticalOrphans(currentCycle: number): ModuleRegistration[] {
  return CONNECTION_REGISTRY.filter(
    m => m.status === 'ORPHAN' && (currentCycle - m.cycleCreated) > 2,
  );
}

/**
 * Returns a summary of the registry state.
 */
export function getRegistrySummary(): {
  total: number;
  connected: number;
  orphan: number;
  archived: number;
  deprecated: number;
  orphanPercentage: number;
} {
  const total = CONNECTION_REGISTRY.length;
  const connected = CONNECTION_REGISTRY.filter(m => m.status === 'CONNECTED').length;
  const orphan = CONNECTION_REGISTRY.filter(m => m.status === 'ORPHAN').length;
  const archived = CONNECTION_REGISTRY.filter(m => m.status === 'ARCHIVED').length;
  const deprecated = CONNECTION_REGISTRY.filter(m => m.status === 'DEPRECATED').length;

  return {
    total,
    connected,
    orphan,
    archived,
    deprecated,
    orphanPercentage: Math.round((orphan / total) * 100),
  };
}
